Repository HICC-REBOOT/HICC-REBOOT-Frontend, pull requests merged in 2024-02, with the labels that each got.

#53 [Feat]: 메인페이지 버튼 그라데이션으로 조정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/home/HongMap.tsx
  frontend/src/components/home/JoinUs.tsx
  frontend/src/components/home/style/Activity.style.tsx
  frontend/src/components/home/style/HongMap.style.tsx
  frontend/src/components/home/style/JoinUs.style.tsx
  frontend/src/components/home/style/ProjectList.style.tsx
Labels: design

#67 [Design]:홈 화면 코딩 기호 사이즈 조정(브랜치를 실수로 mypage로 했습니다)
  frontend/src/components/home/firstScreen/Matter.jsx
  frontend/src/components/mypage/style/MyComments.style.tsx
  frontend/src/components/mypage/style/MyWritings.style.tsx
Labels: design

#69 [Fix]: 커뮤니티 목록에서 보더 부분적으로 보이지 않던 문제 해결, 드롭다운 글씨크기 고정
  frontend/src/components/common/dropdown/Dropdown.style.tsx
  frontend/src/components/common/error/GlobalError.tsx
  frontend/src/components/common/error/NotFound.tsx
  frontend/src/components/common/error/style/GlobalError.style.tsx
  frontend/src/components/common/error/style/NotFound.style.tsx
  frontend/src/components/common/header/Header.tsx
  frontend/src/components/common/header/MobileHeader.tsx
  frontend/src/components/common/header/style/Header.style.tsx
  frontend/src/components/common/header/style/MobileHeader.style.tsx
  frontend/src/components/common/tab/Tab.tsx
  frontend/src/components/common/tab/TabElement.tsx
  frontend/src/components/common/tab/style/Tab.style.tsx
  frontend/src/components/common/tab/style/TabElement.style.tsx
  frontend/src/components/community/common/Buttons.tsx
  frontend/src/components/community/common/ImageManager.tsx
  frontend/src/components/community/common/TextareaInForm.tsx
  frontend/src/components/community/common/WriteInfo.tsx
  frontend/src/components/community/common/style/Buttons.style.tsx
  frontend/src/components/community/common/style/ImageManager.style.tsx
  frontend/src/components/community/common/style/TextareaInForm.style.tsx
  frontend/src/components/community/common/style/WriteInfo.style.tsx
  frontend/src/components/community/detail/comment/Comment.tsx
  frontend/src/components/community/detail/comment/EachComment.tsx
  frontend/src/components/community/detail/comment/WriteComment.tsx
  frontend/src/components/community/detail/comment/style/Comment.style.tsx
  frontend/src/components/community/detail/comment/style/EachComment.style.tsx
  frontend/src/components/community/detail/comment/style/WriteComment.style.tsx
  frontend/src/components/community/list/CommunityList.tsx
  frontend/src/components/community/list/EachArticle.tsx
  frontend/src/components/community/list/style/CommunityList.style.tsx
  frontend/src/components/community/list/style/EachArticle.style.tsx
  frontend/src/components/community/update/CommunityUpdate.tsx
  frontend/src/components/community/write/CommunityWrite.tsx
  frontend/src/components/community/write/EachImage.tsx
  frontend/src/components/community/write/style/CommunityWrite.style.tsx
  frontend/src/components/community/write/style/EachImage.style.tsx
Labels: fix

#70 [Fix] 회장 정보를 api를 통해 불러오도록 변경, 엔터 키 입력 제출 활성화
  frontend/src/components/common/footer/Footer.tsx
  frontend/src/components/community/detail/comment/EachComment.tsx
  frontend/src/components/community/detail/comment/WriteComment.tsx
  frontend/src/components/community/list/filter/Filter.tsx
  frontend/src/hooks/useChangeComment.ts
  frontend/src/pages/auth/Login/Login.style.tsx
  frontend/src/pages/auth/Login/Login.tsx
  frontend/src/query/get/useGetFooterInfo.ts
  frontend/src/utils/axios.ts
  frontend/src/utils/keyboard.ts
Labels: fix

#71 fix: 로그아웃 시 이전 내 정보가 남아있던 현상 해결
  frontend/src/auth/login.ts
  frontend/src/auth/logout.ts
  frontend/src/components/common/header/Header.tsx
  frontend/src/components/common/sidebar/Sidebar.tsx
  frontend/src/constants/keys.ts
  frontend/src/pages/auth/Login/Login.tsx
  frontend/src/query/post/usePostLogin.ts
  frontend/src/query/post/usePostLogout.ts
  frontend/tsconfig.paths.json
Labels: fix

#68 [Feat]: 캘린더 api 연결 및 디자인 수정
  frontend/src/components/calendar/CalendarGrid.tsx
  frontend/src/components/calendar/CalendarType.ts
  frontend/src/components/calendar/DatePicker.tsx
  frontend/src/components/calendar/DetailBox.tsx
  frontend/src/components/calendar/EditModal.tsx
  frontend/src/components/calendar/ScheduleCard.tsx
  frontend/src/components/calendar/TypeButton.tsx
  frontend/src/components/calendar/style/CalendarGrid.style.tsx
  frontend/src/components/calendar/style/DatePicker.style.tsx
  frontend/src/components/calendar/style/DatePickerPanel.css
  frontend/src/components/calendar/style/DetailBox.style.tsx
  frontend/src/components/calendar/style/EditModal.style.tsx
  frontend/src/components/calendar/style/ScheduleCard.style.tsx
  frontend/src/components/calendar/style/TypeButton.style.tsx
  frontend/src/constants/keys.ts
  frontend/src/hooks/useCalendarModal.ts
  frontend/src/pages/Calendar.tsx
  frontend/src/query/delete/useDeleteSchedule.tsx
  frontend/src/query/get/useGetCalendarDayInfo.ts
  frontend/src/query/get/useGetCalendarEachInfo.ts
  frontend/src/query/get/useGetCalendarMonthInfo.ts
  frontend/src/query/patch/usePatchSchedule.ts
  frontend/src/query/post/usePostSchedule.ts
  frontend/src/state/calendar.ts
  frontend/src/styles/styled.d.ts
  frontend/src/styles/theme.ts
Labels: feat, refactor, fix, design

#76 [Feature]: mypage 스켈레톤 추가
  frontend/src/components/mypage/MyComments.tsx
  frontend/src/components/mypage/MyWritings.tsx
  frontend/src/components/mypage/mypage/CommentsInner.tsx
  frontend/src/components/mypage/mypage/WritingsInner.tsx
Labels: design

#79 [design]: 회원 라벨 폰트 수정 및 이름 가운데 정렬
  frontend/src/components/mypage/style/MyInfo.style.tsx
Labels: design

#82 [design]: 메인 홈 화면 엑티비티 글자 줄 바꿈 및 위치 수정
  frontend/src/components/home/Activity.tsx
  frontend/src/components/home/style/Activity.style.tsx
Labels: design

#90 Hotfix 반영
  frontend/src/components/mypage/MyInfo.tsx
  frontend/src/components/mypage/style/MyInfo.style.tsx
  frontend/src/pages/auth/Login/Login.style.tsx
  frontend/src/pages/auth/Login/Login.tsx
Labels: design
