Repository HICC-REBOOT/HICC-REBOOT-Frontend, pull requests merged in 2024-01, with the labels that each got.

#15 [Feat] 멀티 셀렉트 기능 추가, 페이지네이션에 무한스크롤 기능 확장
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/font/area/Area-Bold.woff2
  frontend/src/assets/font/area/Area-Extrabold.woff2
  frontend/src/assets/font/source-sans-pro/SourceSansPro-Bold.woff2
  frontend/src/assets/font/source-sans-pro/SourceSansPro-ExtraLight.woff2
  frontend/src/assets/font/source-sans-pro/SourceSansPro-Light.woff2
  frontend/src/assets/font/source-sans-pro/SourceSansPro-Regular.woff2
  frontend/src/assets/image/arrow.svg
  frontend/src/assets/mediaQuery/Desktop.tsx
  frontend/src/assets/mediaQuery/Mobile.tsx
  frontend/src/assets/mediaQuery/Tablet.tsx
  frontend/src/assets/mediaQuery/index.ts
  frontend/src/assets/temp.ts
  frontend/src/components/Temp/style/temp.style.tsx
  frontend/src/components/Temp/temp.tsx
  frontend/src/components/temp.tsx
  frontend/src/constants/CollegeData.ts
  frontend/src/constants/breakpoint.ts
  frontend/src/constants/keys.ts
  frontend/src/constants/token.ts
  frontend/src/custom.d.ts
  frontend/src/hooks/useInnerWidth.ts
  frontend/src/libs/select/MultiSelect.style.tsx
  frontend/src/libs/select/MultiSelect.tsx
  frontend/src/query/get/useServerSidePagination.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/styles/styled.d.ts
  frontend/src/styles/theme.ts
  frontend/src/utils/axios.ts
Labels: feat

#16 [Feat]: 헤더, 푸터 생성
  frontend/docs/jinhokim98.md
  frontend/public/index.html
  frontend/src/assets/font/source-sans-pro/SourceSansPro-Bold.woff2
  frontend/src/assets/font/source-sans-pro/SourceSansPro-Regular.woff2
  frontend/src/assets/font/source-sans-pro/SourceSansPro-Semibold.woff2
  frontend/src/assets/image/Icon_large.svg
  frontend/src/assets/image/demologo.png
  frontend/src/components/Temp/temp.tsx
  frontend/src/components/common/footer/Footer.style.tsx
  frontend/src/components/common/footer/Footer.tsx
  frontend/src/components/common/header/Header.style.tsx
  frontend/src/components/common/header/Header.tsx
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/layout/style/Layout.style.tsx
  frontend/src/constants/route.ts
  frontend/src/styles/GlobalStyle.ts
Labels: design

#17 [Feat]: 캘린더 일정 관리
  frontend/docs/iOdiO89.md
  frontend/src/App.tsx
  frontend/src/components/calendar/CalendarGrid.tsx
  frontend/src/components/calendar/style/CalendarGrid.style.tsx
  frontend/src/pages/Calendar/Calendar.tsx
  frontend/src/pages/Calendar/style/Calendar.style.tsx
Labels: design

#18 [Feat]: add components for firstscreen and number table in home page
  frontend/docs/JunhoKim.md
  frontend/src/components/home/FirstScreen.tsx
  frontend/src/components/home/NumberTable.tsx
  frontend/src/components/home/style/FirstScreen.style.tsx
  frontend/src/components/home/style/NumberTable.style.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Main.tsx
Labels: design

#19 fix: 라우팅 상수화적용 및 Activity 수정, style z-index 상수화
  frontend/docs/jinhokim98.md
  frontend/src/App.tsx
  frontend/src/components/common/header/Header.style.tsx
  frontend/src/constants/style.ts
  frontend/src/pages/Home.tsx
Labels: fix

#20 [Feat] 탭, 페이지네이션, 컨펌, 맨 위로 버튼, 사이드바 구현
  frontend/docs/jinhokim98.md
  frontend/src/App.tsx
  frontend/src/assets/image/arrow.svg
  frontend/src/assets/image/icon/arrowUp.svg
  frontend/src/assets/image/icon/hamburger.svg
  frontend/src/assets/mediaQuery/NotDesktop.tsx
  frontend/src/assets/mediaQuery/index.ts
  frontend/src/components/Temp/index.ts
  frontend/src/components/Temp/temp.tsx
  frontend/src/components/Temp/temp1.tsx
  frontend/src/components/Temp/temp2.tsx
  frontend/src/components/Temp/temp3.tsx
  frontend/src/components/common/header/Header.tsx
  frontend/src/components/common/header/MobileHeader.style.tsx
  frontend/src/components/common/header/MobileHeader.tsx
  frontend/src/components/common/header/index.ts
  frontend/src/components/common/pagination/Pagination.style.tsx
  frontend/src/components/common/pagination/PaginationComponent.tsx
  frontend/src/components/common/popup/confirm/CommonConfirm.css
  frontend/src/components/common/popup/confirm/Confirm.tsx
  frontend/src/components/common/sidebar/Sidebar.style.tsx
  frontend/src/components/common/sidebar/Sidebar.tsx
  frontend/src/components/common/tab/Tab.style.tsx
  frontend/src/components/common/tab/Tab.tsx
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/layout/style/Layout.style.tsx
  frontend/src/components/utils/MoveToTheTopButton.tsx
  frontend/src/constants/common.ts
  frontend/src/constants/keys.ts
  frontend/src/constants/style.ts
  frontend/src/hooks/useSidebar.ts
  frontend/src/libs/pagination/PaginationComponent.tsx
  frontend/src/libs/pagination/style/Pagination.css
  frontend/src/libs/store/sidebarState.ts
  frontend/src/pages/temp/Temp.tsx
  frontend/src/query/get/useServerSidePagination.tsx
Labels: feat, design

#23 Feature/home
  frontend/docs/JunhoKim.md
  frontend/src/assets/image/joinus_large.svg
  frontend/src/assets/image/joinus_large_mobile.svg
  frontend/src/assets/image/joinus_small.svg
  frontend/src/assets/image/joinus_small_mobile.svg
  frontend/src/components/Temp/style/temp.style.tsx
  frontend/src/components/home/Activity.tsx
  frontend/src/components/home/HongMap.tsx
  frontend/src/components/home/JoinUs.tsx
  frontend/src/components/home/ProjectList.tsx
  frontend/src/components/home/RecentNews.tsx
  frontend/src/components/home/style/Activity.style.tsx
  frontend/src/components/home/style/HongMap.style.tsx
  frontend/src/components/home/style/JoinUs.style.tsx
  frontend/src/components/home/style/ProjectList.style.tsx
  frontend/src/components/home/style/RecentNews.style.tsx
  frontend/src/pages/Home.tsx
Labels: design

#26 [Feat] 헤더 로고 삽입, 드롭다운 스타일 적용, 로딩화면 제작, 404페이지 제작
  frontend/docs/jinhokim98.md
  frontend/src/App.tsx
  frontend/src/assets/image/404big.png
  frontend/src/assets/image/404small.png
  frontend/src/assets/image/logo.svg
  frontend/src/components/common/dropdown/Dropdown.style.tsx
  frontend/src/components/common/error/NotFound.style.tsx
  frontend/src/components/common/error/NotFound.tsx
  frontend/src/components/common/header/Header.style.tsx
  frontend/src/components/common/header/Header.tsx
  frontend/src/components/common/header/MobileHeader.style.tsx
  frontend/src/components/common/loading/Loading.style.tsx
  frontend/src/components/common/loading/Loading.tsx
  frontend/src/components/common/popup/confirm/CommonConfirm.css
  frontend/src/components/common/popup/confirm/Confirm.tsx
  frontend/src/components/common/popup/confirm/ExtensionConfirm.css
  frontend/src/components/common/popup/confirm/ExtensionConfirm.tsx
  frontend/src/components/common/sidebar/Sidebar.style.tsx
  frontend/src/components/common/sidebar/Sidebar.tsx
  frontend/src/components/community/detail/ArticleDetail.tsx
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/utils/moveToTheTopButton/MoveToTheTopButton.style.tsx
  frontend/src/components/utils/moveToTheTopButton/MoveToTheTopButton.tsx
  frontend/src/constants/keys.ts
  frontend/src/constants/route.ts
  frontend/src/constants/style.ts
  frontend/src/query/get/useGetFooterInfo.ts
Labels: feat, fix, design

#29 [Fix] 게시판 상세 스타일 수정, 라디오 버튼, 인증
  frontend/docs/jinhokim98.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/auth/login.ts
  frontend/src/auth/logout.ts
  frontend/src/auth/reissue.ts
  frontend/src/components/Temp/temp2.tsx
  frontend/src/components/common/dropdown/Dropdown.style.tsx
  frontend/src/components/common/footer/Footer.style.tsx
  frontend/src/components/common/radio/EachOption.tsx
  frontend/src/components/common/radio/RadioGroup.tsx
  frontend/src/components/common/tab/Tab.style.tsx
  frontend/src/components/community/CommunityType.ts
  frontend/src/components/community/common/Buttons.style.tsx
  frontend/src/components/community/common/Buttons.tsx
  frontend/src/components/community/common/WriteInfo.tsx
  frontend/src/components/community/detail/ArticleDetail.tsx
  frontend/src/components/community/detail/comment/Comment.tsx
  frontend/src/components/community/detail/comment/EachComment.style.tsx
  frontend/src/components/community/detail/comment/EachComment.tsx
  frontend/src/components/community/detail/comment/WriteComment.style.tsx
  frontend/src/components/community/detail/content/Content.tsx
  frontend/src/components/community/detail/nestedComment/NestedComment.tsx
  frontend/src/components/community/list/CommunityList.tsx
  frontend/src/components/community/list/CommunityListInner.style.tsx
  frontend/src/components/community/list/CommunityListInner.tsx
  frontend/src/components/community/list/EachArticle.style.tsx
  frontend/src/components/community/list/EachArticle.tsx
  frontend/src/components/community/loading/EachBox.tsx
  frontend/src/components/community/loading/Skeleton.style.tsx
  frontend/src/components/community/loading/Skeleton.tsx
  frontend/src/components/layout/style/Layout.style.tsx
  frontend/src/constants/keys.ts
  frontend/src/hooks/useRadio.ts
  frontend/src/libs/store/radioStste.ts
  frontend/src/pages/community/Community.style.tsx
  frontend/src/query/delete/useDeleteComment.ts
  frontend/src/query/delete/useDeleteNestedComment.ts
  frontend/src/query/get/useGetArticleDetail.ts
  frontend/src/query/get/useGetNestedComment.ts
  frontend/src/query/get/useGetParentComment.ts
  frontend/src/query/post/usePostComment.ts
  frontend/src/query/post/usePostNestedComment.ts
  frontend/src/query/temp.ts
  frontend/src/utils/axios.ts
  frontend/src/utils/cookie.ts
  frontend/src/utils/time.ts
Labels: feat, fix, design

#27 [FEAT]: 캘린더 반응형 작업 및 interaction 추가
  frontend/.eslintrc.json
  frontend/docs/iOdiO89.md
  frontend/src/components/calendar/CalendarGrid.tsx
  frontend/src/components/calendar/DatePicker.tsx
  frontend/src/components/calendar/DetailBox.tsx
  frontend/src/components/calendar/EditModal.tsx
  frontend/src/components/calendar/style/CalendarGrid.style.tsx
  frontend/src/components/calendar/style/DatePicker.style.tsx
  frontend/src/components/calendar/style/DetailBox.style.tsx
  frontend/src/components/calendar/style/EditModal.style.tsx
  frontend/src/components/calendar/style/ScheduleCard.style.tsx
  frontend/src/components/calendar/style/TypeButton.style.tsx
  frontend/src/hooks/useCalendarModal.ts
  frontend/src/pages/Calendar.tsx
  frontend/src/state/calendar.ts
Labels: feat, refactor, design

#28 [Feat] 마이페이지 프레임 작업
  frontend/docs/JunhoKim.md
  frontend/src/App.tsx
  frontend/src/assets/image/icon/check.svg
  frontend/src/assets/image/icon/magnifier.svg
  frontend/src/components/common/popup/withdrawal/withdrawal.style.css
  frontend/src/components/common/popup/withdrawal/withdrawal.tsx
  frontend/src/components/mypage/Dropdown.tsx
  frontend/src/components/mypage/DropdownIndicator.tsx
  frontend/src/components/mypage/MyComments.tsx
  frontend/src/components/mypage/MyInfo.tsx
  frontend/src/components/mypage/MyPageComponent.tsx
  frontend/src/components/mypage/MyWritings.tsx
  frontend/src/components/mypage/OptionType.ts
  frontend/src/components/mypage/index.ts
  frontend/src/components/mypage/style/Dropdown.style.tsx
  frontend/src/components/mypage/style/MyComments.style.tsx
  frontend/src/components/mypage/style/MyPageComponent.style.tsx
  frontend/src/components/mypage/style/MyWritings.style.tsx
  frontend/src/components/mypage/style/myInfo.style.tsx
  frontend/src/constants/keys.ts
  frontend/src/constants/route.ts
  frontend/src/pages/MyInfo.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/query/get/useGetMyArticles.ts
  frontend/src/query/get/useGetMyComments.ts
  frontend/src/query/get/useGetProfile.ts
Labels: design

#31 [Feat]: 로그인 페이지 초안
  frontend/docs/iOdiO89.md
  frontend/src/App.tsx
  frontend/src/pages/Login/Login.style.tsx
  frontend/src/pages/Login/Login.tsx
Labels: feat, design

#32 [Feat]: 게시판 api 연결 코드 작성
  frontend/.eslintrc.json
  frontend/docs/jinhokim98.md
  frontend/src/App.tsx
  frontend/src/assets/image/icon/trash.svg
  frontend/src/auth/login.ts
  frontend/src/auth/reissue.ts
  frontend/src/components/community/CommunityType.ts
  frontend/src/components/community/common/ImageManager.style.tsx
  frontend/src/components/community/common/ImageManager.tsx
  frontend/src/components/community/common/TextareaInForm.style.tsx
  frontend/src/components/community/common/TextareaInForm.tsx
  frontend/src/components/community/detail/ArticleDetail.tsx
  frontend/src/components/community/detail/content/Content.tsx
  frontend/src/components/community/index.ts
  frontend/src/components/community/list/CommunityList.tsx
  frontend/src/components/community/list/CommunityListInner.tsx
  frontend/src/components/community/list/filter/Filter.tsx
  frontend/src/components/community/update/CommunityUpdate.tsx
  frontend/src/components/community/write/CommunityWrite.style.tsx
  frontend/src/components/community/write/CommunityWrite.tsx
  frontend/src/components/community/write/EachImage.style.tsx
  frontend/src/components/community/write/EachImage.tsx
  frontend/src/constants/keys.ts
  frontend/src/constants/route.ts
  frontend/src/hooks/useRadio.ts
  frontend/src/libs/store/radioState.ts
  frontend/src/query/delete/useDeleteArticle.ts
  frontend/src/query/get/useGetLatestNews.tsx
  frontend/src/query/patch/usePatchArticle.ts
  frontend/src/query/post/usePostArticle.ts
  frontend/src/utils/axios.ts
  frontend/src/utils/axiosInstance.ts
  frontend/src/utils/image/fetchPresignedUrl.ts
  frontend/src/utils/image/imageType.ts
  frontend/src/utils/image/processNewImage.ts
  frontend/src/utils/image/uploadImageToS3.ts
  frontend/src/utils/request.ts
  frontend/src/utils/time.ts
Labels: feat, fix

#34 [Fix]: 글로벌 에러 화면, 확장 모달 이슈 해결
  frontend/docs/jinhokim98.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/auth/login.ts
  frontend/src/auth/logout.ts
  frontend/src/auth/reissue.ts
  frontend/src/components/Temp/temp2.tsx
  frontend/src/components/Temp/temp3.tsx
  frontend/src/components/common/error/GlobalError.style.tsx
  frontend/src/components/common/error/GlobalError.tsx
  frontend/src/components/common/popup/confirm/ExtensionConfirm.css
  frontend/src/components/common/popup/confirm/ExtensionConfirm.tsx
  frontend/src/components/common/popup/confirm/ExtensionModal.style.tsx
  frontend/src/components/common/popup/confirm/ExtensionModal.tsx
  frontend/src/components/common/radio/EachOption.tsx
  frontend/src/components/common/radio/RadioGroup.tsx
  frontend/src/components/common/sidebar/Sidebar.style.tsx
  frontend/src/components/home/Activity.tsx
  frontend/src/components/home/activityBox/ActivityBox.style.tsx
  frontend/src/components/home/activityBox/ActivityBox.tsx
  frontend/src/components/home/style/Activity.style.tsx
  frontend/src/components/layout/Layout.tsx
  frontend/src/constants/keys.ts
  frontend/src/constants/style.ts
  frontend/src/hooks/useAuth.ts
  frontend/src/hooks/useRadio.ts
  frontend/src/libs/store/login.ts
  frontend/src/libs/store/radioState.ts
  frontend/src/query/get/useGetJoinedPeopleNumber.ts
  frontend/src/query/get/useGetLatestNews.ts
  frontend/src/query/get/useGetUserInfo.ts
  frontend/src/utils/axios.ts
Labels: fix

#35 [Fix]: 로그인 페이지 Bug Fix
  frontend/src/pages/Login/Login.style.tsx
Labels: fix

#36 [Fix]: 공통 파트 수정사항 반영
  frontend/docs/jinhokim98.md
  frontend/package.json
  frontend/src/assets/image/icon/accountCircle.svg
  frontend/src/assets/image/icon/user.svg
  frontend/src/components/Temp/temp3.tsx
  frontend/src/components/common/dropdown/Arrow.style.tsx
  frontend/src/components/common/dropdown/Dropdown.style.tsx
  frontend/src/components/common/dropdown/DropdownIndicator.tsx
  frontend/src/components/common/header/Header.style.tsx
  frontend/src/components/common/header/Header.tsx
  frontend/src/components/common/header/MobileHeader.style.tsx
  frontend/src/components/common/header/MobileHeader.tsx
  frontend/src/components/common/popup/confirm/Confirm.tsx
  frontend/src/components/common/popup/confirm/ExtensionModal.tsx
  frontend/src/components/common/popup/withdrawal/withdrawal.tsx
  frontend/src/components/common/radio/EachOption.tsx
  frontend/src/components/common/radio/RadioGroup.style.tsx
  frontend/src/components/common/radio/RadioType.ts
  frontend/src/components/common/sidebar/Sidebar.style.tsx
  frontend/src/components/common/sidebar/Sidebar.tsx
  frontend/src/components/common/tab/Tab.style.tsx
  frontend/src/components/common/tab/Tab.tsx
  frontend/src/components/common/tab/TabElement.style.tsx
  frontend/src/components/common/tab/TabElement.tsx
  frontend/src/constants/keys.ts
  frontend/src/hooks/useAuth.ts
  frontend/src/libs/store/adminState.ts
  frontend/src/pages/temp/Temp.tsx
  frontend/src/query/get/useGetUserInfo.ts
Labels: fix

#39 [Feat] Mypage 버그 수정 및 비밀번호 기능 추가
  frontend/docs/JunhoKim.md
  frontend/src/components/mypage/MyComments.tsx
  frontend/src/components/mypage/MyInfo.tsx
  frontend/src/components/mypage/MyWritings.tsx
  frontend/src/components/mypage/style/MyComments.style.tsx
  frontend/src/components/mypage/style/MyInfo.style.tsx
  frontend/src/components/mypage/style/MyWritings.style.tsx
Labels: feat, fix, design

#40 [Fix]: 마이 페이지 내가 쓴 글 및 댓글 2줄 이상 넘어가는 내용의 경우 ..표시
  frontend/src/components/mypage/MyComments.tsx
  frontend/src/components/mypage/MyWritings.tsx
  frontend/src/components/mypage/style/MyComments.style.tsx
  frontend/src/components/mypage/style/MyInfo.style.tsx
  frontend/src/components/mypage/style/MyWritings.style.tsx
Labels: fix
